default_platform(:android)

platform :android do
	# p	revious_build_number = google_play_track_version_codes(
	# 	package_name: app_id,
	# 	track: "internal",
	# 	json_key: json_key_file_path,
	#   )[0]
	  
	#   current_build_number = previous_build_number + 1
	  
	#   increment_version_code(
	# 	gradle_file_path: gradle_file_path,
	# 	version_code: current_build_number
	#   )


  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    bundle_folder = "#{File.expand_path(File.dirname(__FILE__))}/../build/app/outputs/bundle/release"
    # bundle_folder = "#{File.expand_path(File.dirname(__FILE__))}/../../build/app/outputs/bundle/release"
    gradle(task: 'clean')
	gradle(
		task: "bundle",
		build_type: 'Release',
	 )
	 upload_to_play_store(
		track: 'internal',
		skip_upload_metadata: true,
		skip_upload_images: true,
		skip_upload_changelogs: true,
		skip_upload_screenshots: true,
	  )
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
end
