default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Bin_App_client.xcodeproj")
    build_app(scheme: "Bin_App_client")
    upload_to_testflight
  end
end
